### ISSUE TITLE
Can you put the selected values into a form?  

### ISSUE THREAD

**Issue by owen-kellie-smith** [mateagar/fieldChooser#12]
How would you do that?

e.g. for the list that has been created have the same effect as selected options in a 
```
<select multiple>
</select>
``` 

control

**Comment by dgent81** [comment]
I want to call the method that can show all the fields left in the source list.  I am not using the destination list in my application and it is hidden but users can via another feature remove items from the sort list.  I am just using the source list and it is working well for my needs, but I can not determine the syntax to call the fieldList method to get all the left items in the source list
